project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "2024 Election Results"
  navbar:
    background: primary
    search: true
    pinned: true
    left: 
      - pages/nc.qmd
      - pages/tx.qmd
      
date: last-modified
date-format: "MMMM D YYYY, hh:mm:ss a z"
author: 
- Joseph R. Loffredo, Mason Reece, Jack Williams, Charles Stewart III
affiliation: Massachusetts Institute of Technology
page-layout: full

format:
  html:
    theme: cosmo
    toc: true
    echo: false
    message: false
    warning: false