project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "pages/*.qmd"
    - "!archive/"
    - "!pages/AZ_Pima.qmd"
    - "!pages/MI_Macomb.qmd"
    - "!pages/MI_Eaton.qmd"

website:
  title: "2024 Election Results"
  navbar:
    background: primary
    search: false
    pinned: true
    left: 
      - "pages/AZ_Maricopa.qmd"
      # - "pages/AZ_Pima.qmd"
      - "pages/GA.qmd"
      # - "pages/MI_Eaton.qmd"
      - "pages/MI_Ingham.qmd"
      # - "pages/MI_Macomb.qmd"
      - "pages/MI_Oakland.qmd"
      - "pages/NC.qmd"
      - "pages/PA_Allegheny.qmd"
      - "pages/PA_Delaware.qmd"
      - "pages/PA_Philadelphia.qmd"
      
date: now
date-format: "MMM D HH:mm:ss A z"
author: 
- Joseph R. Loffredo, Mason Reece, Charles Stewart III
affiliation: Massachusetts Institute of Technology
page-layout: full
embed-resources: true

format:
  html:
    theme: cosmo
    toc: true
    toc-location: body
    echo: false
    message: false
    warning: false
    minimal: true